/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LEGEND
 */
import javax.swing.JOptionPane;
import java.sql.*;
import net.proteanit.sql.DbUtils;

public class work extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    boolean y, x, z, k, i = false;
    PreparedStatement pst = null;

    public work() {
        initComponents();
        conn = FClass.Connectdb();
        Updat();
        Updat3();
        Updatif();
        Updat2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTabbedPane();
        jp1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        b4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        jb5 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        cc2 = new javax.swing.JComboBox<>();
        cc1 = new javax.swing.JComboBox<>();
        cc3 = new javax.swing.JComboBox<>();
        cc4 = new javax.swing.JComboBox<>();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        co2 = new javax.swing.JComboBox<>();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cc5 = new javax.swing.JComboBox<>();
        cc6 = new javax.swing.JComboBox<>();
        cc7 = new javax.swing.JComboBox<>();
        jl = new javax.swing.JLabel();
        jll = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        tt1 = new javax.swing.JTextField();
        tt2 = new javax.swing.JTextField();
        tt3 = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ttt2 = new javax.swing.JTextField();
        ttt3 = new javax.swing.JTextField();
        co4 = new javax.swing.JComboBox<>();
        tbb3 = new javax.swing.JButton();
        tbb4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("معمل المرج الاخضر لصناعة الأعلاف");

        jt1.setForeground(new java.awt.Color(0, 0, 153));
        jt1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt1MouseClicked(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N

        l1.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(204, 0, 0));
        l1.setText("فاتورة جديده");

        tb1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        b4.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 204));
        b4.setText("الفاتورة الحاليه");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 204));
        b3.setText("المبيعات");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 204));
        b2.setText("المشتريات");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        jb1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jb1.setForeground(new java.awt.Color(0, 51, 204));
        jb1.setText("بحث");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jb2.setForeground(new java.awt.Color(0, 51, 204));
        jb2.setText("جديد");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "نوع الفاتورة", "مشتريات", "مبيعات" }));
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                c1MouseReleased(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jb5.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jb5.setForeground(new java.awt.Color(0, 0, 204));
        jb5.setText("كشف حساب");

        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
        });

        cc2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cc1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cc3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        cc4.setMaximumRowCount(50);
        cc4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cc4ItemStateChanged(evt);
            }
        });
        cc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cc4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cc4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cc4MouseReleased(evt);
            }
        });
        cc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc4ActionPerformed(evt);
            }
        });

        t4.setText("عنوان العميل");
        t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t4FocusGained(evt);
            }
        });

        t5.setText("تلفون العميل");
        t5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t5FocusGained(evt);
            }
        });

        co2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الصنف", "ذرة صفراء", "نخالة", "كسبة قطن", "شعير", "بريمكس فروج", "بريمكس ابقار", "كالسيوم", "صويا", "علف حبوب", "علف تسمين مجروش", "علف تسمين حبوب", "علف فروج م1", "علف فروج م2", "سمسم", "ملح", "فيتامينات", "معادن" }));
        co2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                co2MouseReleased(evt);
            }
        });
        co2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co2ActionPerformed(evt);
            }
        });

        t6.setText("عدد");
        t6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t6FocusGained(evt);
            }
        });

        t7.setText("السعر");
        t7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t7FocusGained(evt);
            }
        });

        t8.setText("القيمه");
        t8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t8FocusGained(evt);
            }
        });

        t9.setText("المدفوعات");
        t9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t9FocusGained(evt);
            }
        });

        t10.setText("ملاحظات");
        t10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t10FocusGained(evt);
            }
        });

        b1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 204));
        b1.setText("ادخال");
        b1.setFocusable(false);
        b1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jb3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jb3.setForeground(new java.awt.Color(51, 0, 204));
        jb3.setText("بحث");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setText("كشف");

        cc5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cc5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cc6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cc6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cc7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cc7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jl.setText("من");

        jll.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jll.setText("الى");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cc4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(c1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(co2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb5)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(cc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(cc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jll))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(cc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(cc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(b4)
                        .addGap(18, 18, 18)
                        .addComponent(b3)
                        .addGap(18, 18, 18)
                        .addComponent(b2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b4)
                        .addComponent(b3)
                        .addComponent(b2))
                    .addComponent(l1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cc4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(co2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("فاتورة جديدة", jPanel6);

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jt1.addTab("فاتورة", jp1);

        jp2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jp2FocusGained(evt);
            }
        });

        bt1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 153, 0));
        bt1.setText("العملاء");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 153, 0));
        bt2.setText("الموردين");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        tb2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb2);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("ادخال عميل/مورد");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("العميل او المورد");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("الهاتف");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("العنوان");

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("تعديل عميل/مورد");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(204, 0, 0));
        bt3.setText("حذف");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        tt1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        tt2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        tt3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        lb2.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(204, 0, 0));
        lb2.setText("العملاء");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tt1)
                            .addComponent(tt2)
                            .addComponent(tt3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt2)
                        .addComponent(bt1)))
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tt3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jt1.addTab("قائمة العملاء و الموردين", jp2);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("سعر الشراء");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("سعر البيع");

        ttt2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ttt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttt2ActionPerformed(evt);
            }
        });

        ttt3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        co4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الصنف", "ذرة صفراء", "نخالة", "كسبة قطن", "شعير", "بريمكس فروج", "بريمكس ابقار", "كالسيوم", "صويا", "علف حبوب", "علف تسمين مجروش", "علف تسمين حبوب", "علف فروج م1", "علف فروج م2", "سمسم", "ملح", "فيتامينات", "معادن" }));
        co4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co4ActionPerformed(evt);
            }
        });

        tbb3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        tbb3.setForeground(new java.awt.Color(0, 102, 0));
        tbb3.setText("اضافة صنف");
        tbb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbb3ActionPerformed(evt);
            }
        });

        tbb4.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        tbb4.setForeground(new java.awt.Color(255, 153, 0));
        tbb4.setText("تعديل صنف");
        tbb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbb4ActionPerformed(evt);
            }
        });

        tb3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb3);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("حدد صنف لتعديله");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(338, 338, 338))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ttt2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(co4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttt3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(tbb4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(tbb3)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(co4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttt2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ttt3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbb3)
                            .addComponent(tbb4))
                        .addGap(162, 162, 162))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );

        jt1.addTab("قائمة الاصناف", jPanel3);

        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        jt1.addTab("tab4", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jt1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jt1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        l1.setText("فاتورة جديدة");
        try {
            String sql = "insert into invoice (الصنف,عدد,السعر,القيمه,اجمالي_الفاتورة,المدفوعات,ملاحظات) values(?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, co2.getItemAt(co2.getSelectedIndex()));
            pst.setString(2, t6.getText());
            pst.setString(3, t7.getText());
            pst.setString(4, t8.getText());
            pst.setString(5, "");
            pst.setString(6, t9.getText());
            pst.setString(7, t10.getText());
            pst.execute();
            pst.close();
            Updatif();
            y = true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        if (c1.getSelectedIndex() == 1) {
            try {
                String sql = "insert into pruch (تاريخ_الفاتورة,اسم_المورد,صنف,عدد,السعر,القيمة,مدفوعات,ملاحظة) values(?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cc1.getSelectedItem().toString() + "-" + cc2.getSelectedItem().toString() + "-" + cc3.getSelectedItem().toString());
                pst.setString(2, cc4.getSelectedItem().toString());
                pst.setString(3, co2.getItemAt(co2.getSelectedIndex()));
                pst.setString(4, t6.getText());
                pst.setString(5, t7.getText());
                pst.setString(6, t8.getText());
                pst.setString(7, t9.getText());
                pst.setString(8, t10.getText());
                pst.execute();
                pst.close();
                Updat();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
    }//GEN-LAST:event_b1ActionPerformed
        if (c1.getSelectedIndex() == 2) {
            try {
                String sql = "insert into sales (تاريخ_الفاتورة,اسم_المورد,صنف,عدد,السعر,القيمة,مدفوعات,ملاحظة) values(?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cc1.getSelectedItem().toString() + "-" + cc2.getSelectedItem().toString() + "-" + cc3.getSelectedItem().toString());
                pst.setString(2, cc4.getSelectedItem().toString());
                pst.setString(3, co2.getItemAt(co2.getSelectedIndex()));
                pst.setString(4, t6.getText());
                pst.setString(5, t7.getText());
                pst.setString(6, t8.getText());
                pst.setString(7, t9.getText());
                pst.setString(8, t10.getText());
                pst.execute();
                pst.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }

    }
    private void t6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t6FocusGained
        t6.setText("");
    }//GEN-LAST:event_t6FocusGained

    private void t4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t4FocusGained
        t4.setText("");
    }//GEN-LAST:event_t4FocusGained

    private void t5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t5FocusGained
        t5.setText("");

    }//GEN-LAST:event_t5FocusGained

    private void t7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t7FocusGained
        t7.setText("");
    }//GEN-LAST:event_t7FocusGained

    private void t8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t8FocusGained
        t8.setText("");
    }//GEN-LAST:event_t8FocusGained

    private void t9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t9FocusGained
        t9.setText("");
    }//GEN-LAST:event_t9FocusGained

    private void t10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t10FocusGained
        cc1.setSelectedIndex(0);
        cc3.setSelectedIndex(0);
        cc2.setSelectedIndex(0);
    }//GEN-LAST:event_t10FocusGained

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        y = true;
        l1.setText("فاتورة جديدة");
        Updatif();

    }//GEN-LAST:event_b4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        x = true;
        l1.setText("المشتريات");
        Updatif();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        z = true;
        l1.setText("المبيعات");
        Updatif();
    }//GEN-LAST:event_b3ActionPerformed

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained

        t1.setText("");
    }//GEN-LAST:event_t1FocusGained

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        String n, m;

        if (k) {
            n = "customer";

        } else {
            n = "suplay";

        }
        try {
            int row = tb2.getSelectedRow();
            int calum = tb2.getSelectedColumn();
            String clik = (tb2.getModel().getValueAt(row, 0).toString());
            String sql = "delete from " + n + " where تسلسل=" + clik;
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            Updat2();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void jp2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jp2FocusGained
        y = true;
        k = true;
        Updat2();
    }//GEN-LAST:event_jp2FocusGained

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        y = true;
        k = true;
        lb2.setText("العملاء");
        Updat2();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        z = true;
        k = false;
        lb2.setText("الموردين");
        Updat2();
    }//GEN-LAST:event_bt2ActionPerformed

    private void jt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt1MouseClicked
        y = true;
        k = true;
        lb2.setText("العملاء");
        Updat2();
    }//GEN-LAST:event_jt1MouseClicked

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
        String n = "customer";

        if (k) {
            n = "customer";

        } else {
            n = "suplay";

        }
        try {
            ResultSet rs2 = null;
            int row = tb2.getSelectedRow();
            String clik = (tb2.getModel().getValueAt(row, 0).toString());
            String sql = "select * from " + n + " where تسلسل =?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(clik));
            pst.executeQuery();
            rs2 = pst.executeQuery();

            if (rs2.next()) {

                tt1.setText(rs2.getString(2));
                tt2.setText(rs2.getString(3));
                tt3.setText(rs2.getString(4));
                rs2.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tb2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String n = "customer";

        if (k) {
            n = "customer";
            y = true;

        } else {
            n = "suplay";
            z = true;

        }
        try {
            String sql2 = "insert into " + n + " (العميل,هاتف,عنوان) values(?,?,?)";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, tt1.getText());
            pst.setString(2, tt2.getText());
            pst.setString(3, tt3.getText());
            pst.execute();
            pst.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        if (i) {
            jt1.setSelectedIndex(0);

            i = false;

        }

        tt1.setText("");
        tt2.setText("");
        tt3.setText("");
        Updat2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String n;
        if (k) {
            n = "customer";
        } else {
            n = "suplay";
        }
        try {
            int row = tb2.getSelectedRow();
            String clik = (tb2.getModel().getValueAt(row, 0).toString());
            String sql = "update " + n + " set العميل ='" + tt1.getText() + "' ,هاتف='" + tt2.getText() + "' ,عنوان='" + tt3.getText() + "' where تسلسل=" + clik;
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tt1.setText("");
        tt2.setText("");
        tt3.setText("");
        Updat2();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MouseClicked

        try {
            int row = tb3.getSelectedRow();
            String clik = (tb3.getModel().getValueAt(row, 0).toString());
            String sql = "select * from kinds where تسلسل =" + clik;
            pst = conn.prepareStatement(sql);
            pst.executeQuery();
            rs = pst.executeQuery();

            if (rs.next()) {
                co4.setSelectedIndex(Integer.parseInt(clik));
                ttt2.setText(rs.getString(3));
                ttt3.setText(rs.getString(4));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_tb3MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        Updat3();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        Updat3();
    }//GEN-LAST:event_jPanel3FocusGained

    private void tbb4ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int row = tb3.getSelectedRow();
            String clik = (tb3.getModel().getValueAt(row, 0).toString());
            String sql = "update kinds set الصنف ='" + co4.getSelectedItem().toString() + "' ,سعر_الشراء='" + ttt2.getText() + "' ,سعر_البيع='" + ttt3.getText() + "' where تسلسل=" + clik;
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "الرجاء نحديد صنف للتعديل");
        }
        co4.setSelectedIndex(0);
        ttt2.setText("");
        ttt3.setText("");
        Updat3();
    }


    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        Updat3();
    }//GEN-LAST:event_jPanel4FocusGained

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        Updat3();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void tbb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbb3ActionPerformed
        try {
            String sql2 = "insert into kinds (الصنف,سعر_الشراء,سعر_البيع) values(?,?,?)";
            pst = conn.prepareStatement(sql2);
            pst.setString(1, co4.getSelectedItem().toString());
            pst.setString(2, ttt2.getText());
            pst.setString(3, ttt3.getText());
            pst.execute();
            pst.close();
            Updat3();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbb3ActionPerformed

    private void co4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_co4ActionPerformed

    private void ttt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttt2ActionPerformed

    private void cc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc4ActionPerformed

    }//GEN-LAST:event_cc4ActionPerformed

    private void cc4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cc4ItemStateChanged
        if (cc4.getSelectedItem().toString() == "عميل جديد") {
            jt1.setSelectedIndex(1);
            i = true;

        }
        String s = "customer";
        if (k) {
            s = "customer";
        } else {
            s = "suplay";
        }
        if (cc4.getSelectedItem().toString() != "عميل جديد" && cc4.getSelectedItem().toString() != "اسم العميل" && cc4.getSelectedItem().toString() != "") {

            try {
                rs.close();
                String sql2 = "select * from " + s + " where تسلسل=?";

                pst = conn.prepareStatement(sql2);
                pst.setInt(1, cc4.getSelectedIndex());
                rs = pst.executeQuery();
                if (rs.next()) {
                    String sql = rs.getString(3);
                    t4.setText(sql);
                    t5.setText(rs.getString(4));
                    pst.close();

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_cc4ItemStateChanged

    private void cc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cc4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cc4MouseClicked

    private void cc4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cc4MousePressed

    }//GEN-LAST:event_cc4MousePressed

    private void co2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_co2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed

    }//GEN-LAST:event_c1ActionPerformed

    private void c1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseReleased

    }//GEN-LAST:event_c1MouseReleased

    private void co2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_co2MouseReleased

    private void cc4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cc4MouseReleased

    }//GEN-LAST:event_cc4MouseReleased

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        if (c1.getSelectedItem().toString() == "مشتريات") {
            y = false;
            z = true;
            Updat2();
            Updatcom();
            cc4.setSelectedIndex(0);
        } else if (c1.getSelectedItem().toString() == "مبيعات") {
            y = true;
            z = false;
            Updat2();
            Updatcom();
            cc4.setSelectedIndex(0);
        }
    }//GEN-LAST:event_c1ItemStateChanged

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        co2.setVisible(false);
        t6.setVisible(false);
        t7.setVisible(false);
        t8.setVisible(false);
        t9.setVisible(false);
        t10.setVisible(false);
        jb3.setVisible(true);
        b1.setVisible(false);
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        co2.setVisible(true);
        t6.setVisible(true);
        t7.setVisible(true);
        t8.setVisible(true);
        t9.setVisible(true);
        t10.setVisible(true);
        jb3.setVisible(false);
        b1.setVisible(true);

    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        String n = "pruch";
        if (c1.getSelectedItem().toString() == "مبيعات") {
            n = "sales";
        } else if (c1.getSelectedItem().toString() == "مشتريات") {
            n = "pruch";
        }
        String sql = "select * from " + n + " where تاريخ_الفاتورة=? AND اسم_المورد=? ";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, cc1.getSelectedObjects().toString() + "-" + cc2.getSelectedItem().toString() + "-" + cc3.getSelectedItem().toString());
            pst.setString(2, cc4.getSelectedItem().toString());
            rs = pst.executeQuery();
            tb1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Updat() {

        String sql = "select * from invoice";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb1.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Updat2() {
        String n = "customer";
        if (y) {
            n = "customer";
        } else if (z) {
            n = "suplay";
        }
        String sql = "select * from " + n;
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb2.setModel(DbUtils.resultSetToTableModel(rs));
            y = false;
            z = false;
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Updatif() {
        if (y) {
            String sql = "select * from invoice";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tb1.setModel(DbUtils.resultSetToTableModel(rs));
                y = false;
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if (x) {
            String sql = "select * from pruch";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tb1.setModel(DbUtils.resultSetToTableModel(rs));
                x = false;
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if (z) {
            String sql = "select * from sales";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                tb1.setModel(DbUtils.resultSetToTableModel(rs));
                z = false;
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void Updat3() {

        String sql = "select * from kinds";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb3.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void Updatcom() {
        int itemCount = cc4.getItemCount();

        for (int i = 0; i < itemCount; i++) {
            cc4.removeItemAt(0);
        }

        cc4.addItem("اسم العميل");
        int p = tb2.getRowCount();
        for (int j = 0; j < p; j++) {
            cc4.addItem(tb2.getValueAt(j, 1).toString());
        }
        cc4.addItem("عميل جديد");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new work().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> cc1;
    private javax.swing.JComboBox<String> cc2;
    private javax.swing.JComboBox<String> cc3;
    private javax.swing.JComboBox<String> cc4;
    private javax.swing.JComboBox<String> cc5;
    private javax.swing.JComboBox<String> cc6;
    private javax.swing.JComboBox<String> cc7;
    private javax.swing.JComboBox<String> co2;
    private javax.swing.JComboBox<String> co4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb5;
    private javax.swing.JLabel jl;
    private javax.swing.JLabel jll;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JTabbedPane jt1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel lb2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    private javax.swing.JButton tbb3;
    private javax.swing.JButton tbb4;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    private javax.swing.JTextField tt3;
    private javax.swing.JTextField ttt2;
    private javax.swing.JTextField ttt3;
    // End of variables declaration//GEN-END:variables
}
